// Code generated by control-plane/cmd/mcpgen from api/openapi.yaml and api/vocabulary.yaml. DO NOT EDIT.

export type VerbClass = "read" | "mutate";
export type Confirm = "none" | "inline" | "approval" | "modal";

export type VerbSpec = {
  readonly class: VerbClass;
  readonly reversible: boolean | null;
  readonly confirm: Confirm;
  readonly icon: string;
  readonly key?: string;
  readonly agentOnly?: boolean;
};

export const verbs = {
  accept: { class: "mutate", reversible: null, confirm: "none", icon: "Check" },
  adopt: { class: "mutate", reversible: true, confirm: "none", icon: "Import" },
  approve: { class: "mutate", reversible: false, confirm: "none", icon: "CheckCircle" },
  archive: { class: "mutate", reversible: true, confirm: "inline", icon: "Archive" },
  average: { class: "mutate", reversible: null, confirm: "none", icon: "Combine" },
  benchmark: { class: "mutate", reversible: null, confirm: "none", icon: "Timer" },
  calibrate: { class: "mutate", reversible: null, confirm: "none", icon: "Settings" },
  cancel: { class: "mutate", reversible: false, confirm: "inline", icon: "Xmark" },
  compare: { class: "read", reversible: null, confirm: "none", icon: "Compress" },
  correct: { class: "mutate", reversible: false, confirm: "none", icon: "TextSquare" },
  deny: { class: "mutate", reversible: false, confirm: "none", icon: "XmarkCircle" },
  edit: { class: "mutate", reversible: true, confirm: "none", icon: "EditPencil" },
  evict: { class: "mutate", reversible: true, confirm: "none", icon: "Upload" },
  export: { class: "mutate", reversible: null, confirm: "none", icon: "ShareIos" },
  freeze: { class: "mutate", reversible: false, confirm: "inline", icon: "Lock" },
  gate: { class: "mutate", reversible: null, confirm: "none", icon: "Filter" },
  get: { class: "read", reversible: null, confirm: "none", icon: "Page" },
  lineage: { class: "read", reversible: null, confirm: "none", icon: "GitFork" },
  list: { class: "read", reversible: null, confirm: "none", icon: "List" },
  materialize: { class: "mutate", reversible: null, confirm: "none", icon: "Download" },
  new: { class: "mutate", reversible: null, confirm: "none", icon: "Plus" },
  note: { class: "mutate", reversible: true, confirm: "none", icon: "Notes" },
  open: { class: "mutate", reversible: null, confirm: "none", icon: "OpenNewWindow" },
  package: { class: "mutate", reversible: false, confirm: "none", icon: "Box" },
  parity: { class: "mutate", reversible: null, confirm: "none", icon: "DoubleCheck" },
  pause: { class: "mutate", reversible: true, confirm: "none", icon: "Pause" },
  pin: { class: "mutate", reversible: true, confirm: "none", icon: "PinSolid" },
  preview: { class: "mutate", reversible: null, confirm: "none", icon: "Eye" },
  promote: { class: "mutate", reversible: null, confirm: "modal", icon: "ArrowUpCircle" },
  register: { class: "mutate", reversible: false, confirm: "inline", icon: "BookmarkBook" },
  reject: { class: "mutate", reversible: false, confirm: "none", icon: "Prohibition" },
  resume: { class: "mutate", reversible: null, confirm: "none", icon: "Forward" },
  retry: { class: "mutate", reversible: null, confirm: "none", icon: "Restart" },
  revert: { class: "mutate", reversible: true, confirm: "none", icon: "UndoAction" },
  revoke: { class: "mutate", reversible: false, confirm: "inline", icon: "KeyMinus" },
  rollback: { class: "mutate", reversible: true, confirm: "none", icon: "Undo" },
  run: { class: "mutate", reversible: null, confirm: "none", icon: "Play" },
  scan: { class: "mutate", reversible: null, confirm: "none", icon: "ScanBarcode" },
  search: { class: "read", reversible: null, confirm: "none", icon: "Search" },
  set: { class: "mutate", reversible: true, confirm: "none", icon: "Pin" },
  stage: { class: "mutate", reversible: null, confirm: "none", icon: "StatUp" },
  sync: { class: "mutate", reversible: true, confirm: "none", icon: "RefreshDouble" },
  wait: { class: "read", reversible: null, confirm: "none", icon: "Hourglass", agentOnly: true },
} as const satisfies Record<string, VerbSpec>;

export type Verb = keyof typeof verbs;

export type OperationSpec = {
  readonly id: string;
  readonly entity: string;
  readonly verb: string;
  readonly kind: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH";
  readonly path: string;
  readonly summary: string;
  readonly planned: number;
  readonly mcp: boolean;
};

export const operations = {
  "agentMessages.new": { id: "agentMessages.new", entity: "agentMessages", verb: "new", kind: "agent_message", method: "POST", path: "/agent-sessions/{id}/agent-messages", summary: "User message with entity references; updates arrive on agent.session.{id}", planned: 1, mcp: false },
  "agentSessions.cancel": { id: "agentSessions.cancel", entity: "agentSessions", verb: "cancel", kind: "agent_session", method: "POST", path: "/agent-sessions/{id}:cancel", summary: "Stop the session's current turn", planned: 1, mcp: false },
  "agentSessions.new": { id: "agentSessions.new", entity: "agentSessions", verb: "new", kind: "agent_session", method: "POST", path: "/projects/{p}/agent-sessions", summary: "Launch Claude Code or opencode in a project worktree", planned: 1, mcp: false },
  "aliases.set": { id: "aliases.set", entity: "aliases", verb: "set", kind: "aliase", method: "PUT", path: "/projects/{p}/aliases/{name}", summary: "Point a project alias at a registry version (baseline is gated, production moves only by promotion)", planned: 1, mcp: false },
  "approvals.approve": { id: "approvals.approve", entity: "approvals", verb: "approve", kind: "approval", method: "POST", path: "/approvals/{id}:approve", summary: "Approve a pending request; the stored request runs as its original actor", planned: 0, mcp: true },
  "approvals.deny": { id: "approvals.deny", entity: "approvals", verb: "deny", kind: "approval", method: "POST", path: "/approvals/{id}:deny", summary: "Deny a pending request; it never runs", planned: 0, mcp: true },
  "approvals.get": { id: "approvals.get", entity: "approvals", verb: "get", kind: "approval", method: "GET", path: "/approvals/{id}", summary: "Get an approval with its stored request and, once approved, the replay's result", planned: 0, mcp: true },
  "approvals.list": { id: "approvals.list", entity: "approvals", verb: "list", kind: "approval", method: "GET", path: "/approvals", summary: "Approvals, pending first, then the most recently decided", planned: 0, mcp: true },
  "audit.list": { id: "audit.list", entity: "audit", verb: "list", kind: "audit_entry", method: "GET", path: "/audit", summary: "The audit log, newest first — every command, denial and failed attempt with its actor and cause", planned: 0, mcp: true },
  "events.list": { id: "events.list", entity: "events", verb: "list", kind: "event", method: "GET", path: "/events", summary: "Events after a sequence number; with Accept text/event-stream, the live stream", planned: 0, mcp: true },
  "help.get": { id: "help.get", entity: "help", verb: "get", kind: "help_article", method: "GET", path: "/help/{id}", summary: "Get a help article (markdown)", planned: 0, mcp: true },
  "help.search": { id: "help.search", entity: "help", verb: "search", kind: "help_article", method: "GET", path: "/help", summary: "Search help articles by text or by context (panel, step kind, error type, field)", planned: 0, mcp: true },
  "jobs.cancel": { id: "jobs.cancel", entity: "jobs", verb: "cancel", kind: "job", method: "POST", path: "/jobs/{id}:cancel", summary: "Cancel a job; a queued job stops at once, a running one when its handler notices", planned: 0, mcp: true },
  "jobs.get": { id: "jobs.get", entity: "jobs", verb: "get", kind: "job", method: "GET", path: "/jobs/{id}", summary: "Get a job", planned: 0, mcp: true },
  "jobs.list": { id: "jobs.list", entity: "jobs", verb: "list", kind: "job", method: "GET", path: "/projects/{p}/jobs", summary: "Jobs of a project, newest first", planned: 0, mcp: true },
  "jobs.wait": { id: "jobs.wait", entity: "jobs", verb: "wait", kind: "job", method: "GET", path: "/jobs/{id}:wait", summary: "Wait until a job ends or the timeout passes, then return it (agents)", planned: 0, mcp: true },
  "me.get": { id: "me.get", entity: "me", verb: "get", kind: "user", method: "GET", path: "/me", summary: "The current actor", planned: 0, mcp: false },
  "mixes.edit": { id: "mixes.edit", entity: "mixes", verb: "edit", kind: "mix", method: "PATCH", path: "/mixes/{id}", summary: "Edit a mix; agent edits land as drafts", planned: 2, mcp: false },
  "mixes.new": { id: "mixes.new", entity: "mixes", verb: "new", kind: "mix", method: "POST", path: "/projects/{p}/mixes", summary: "Save a mix (input_cfg groups, weights, temperature, replay share)", planned: 2, mcp: false },
  "mixes.preview": { id: "mixes.preview", entity: "mixes", verb: "preview", kind: "mix", method: "POST", path: "/projects/{p}/mixes:preview", summary: "Hours per language for a mix without saving it", planned: 2, mcp: false },
  "mounts.list": { id: "mounts.list", entity: "mounts", verb: "list", kind: "mount", method: "GET", path: "/mounts", summary: "Registered mounts and their health", planned: 4, mcp: false },
  "mounts.new": { id: "mounts.new", entity: "mounts", verb: "new", kind: "mount", method: "POST", path: "/mounts", summary: "Register a local path, NFS/SMB path, S3-compatible bucket or Hub source (approval)", planned: 4, mcp: false },
  "projects.archive": { id: "projects.archive", entity: "projects", verb: "archive", kind: "project", method: "POST", path: "/projects/{p}:archive", summary: "Archive a project (soft; reversible)", planned: 0, mcp: true },
  "projects.edit": { id: "projects.edit", entity: "projects", verb: "edit", kind: "project", method: "PATCH", path: "/projects/{p}", summary: "Rename or re-describe a project", planned: 0, mcp: true },
  "projects.get": { id: "projects.get", entity: "projects", verb: "get", kind: "project", method: "GET", path: "/projects/{p}", summary: "Get a project", planned: 0, mcp: true },
  "projects.list": { id: "projects.list", entity: "projects", verb: "list", kind: "project", method: "GET", path: "/projects", summary: "List projects", planned: 0, mcp: true },
  "projects.new": { id: "projects.new", entity: "projects", verb: "new", kind: "project", method: "POST", path: "/projects", summary: "Create a project", planned: 0, mcp: true },
  "registry.search": { id: "registry.search", entity: "registry", verb: "search", kind: "registry_version", method: "GET", path: "/registry", summary: "Search registry versions of every kind (empty until phase 1 registers kinds)", planned: 0, mcp: true },
  "runs.new": { id: "runs.new", entity: "runs", verb: "new", kind: "run", method: "POST", path: "/projects/{p}/runs", summary: "Start a training run; ?dryRun=true returns GPU-hours, card and duration", planned: 2, mcp: false },
  "workspaces.get": { id: "workspaces.get", entity: "workspaces", verb: "get", kind: "workspace", method: "GET", path: "/me/projects/{p}/workspaces/{name}", summary: "Get a saved workspace", planned: 0, mcp: false },
  "workspaces.list": { id: "workspaces.list", entity: "workspaces", verb: "list", kind: "workspace", method: "GET", path: "/me/projects/{p}/workspaces", summary: "The user's saved workspaces in a project (names and revisions, no layouts)", planned: 0, mcp: false },
  "workspaces.set": { id: "workspaces.set", entity: "workspaces", verb: "set", kind: "workspace", method: "PUT", path: "/me/projects/{p}/workspaces/{name}", summary: "Save a workspace layout (If-Match; omit it only to create)", planned: 0, mcp: false },
} as const satisfies Record<string, OperationSpec>;

export type OperationId = keyof typeof operations;
