// Code generated by control-plane/cmd/mcpgen from api/openapi.yaml. DO NOT EDIT.

package cli

// Operations are the commands `cadence <entity> <verb>`: every implemented operation outside the exempt tags.
var Operations = []Operation{
	{
		ID: "adoptions.list", Entity: "adoptions", Verb: "list", Method: "GET", Path: "/projects/{p}/adoptions",
		Summary: "Registry versions the project adopted, with the aliases pointing at each",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "kind", In: "query", Flag: "kind", Type: "string", Description: "Only versions of this kind", Enum: []string{"base_model", "dataset_version", "template"}},
		},
	},
	{
		ID: "agentMessages.list", Entity: "agentMessages", Verb: "list", Method: "GET", Path: "/agent-sessions/{id}/agent-messages",
		Summary: "The session transcript in order, one page after a sequence number",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Agent session id (ses_…)"},
			{Name: "after", In: "query", Flag: "after", Type: "integer", Description: "Only entries with a larger seq (the last seq of the previous page)", Default: "0"},
			{Name: "limit", In: "query", Flag: "limit", Type: "integer", Default: "200"},
		},
	},
	{
		ID: "agentMessages.new", Entity: "agentMessages", Verb: "new", Method: "POST", Path: "/agent-sessions/{id}/agent-messages",
		Summary:        "Send a user message with entity references; the agent answers on agent.session.{id}",
		Description:    "Send a message to an agent session. References (@run:123, @mix:mix_…, @utt:…#t=…) expand into a compact context block for the agent and become its selection://current. Agents cannot send messages to sessions.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Agent session id (ses_…)"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "references", Type: "array of object"},
			{Name: "text", Required: true, Type: "string"},
		}},
	},
	{
		ID: "agentModels.list", Entity: "agentModels", Verb: "list", Method: "GET", Path: "/catalog/agent-models",
		Summary: "Agent models per driver, with the default the wizard picks",
	},
	{
		ID: "agentProfile.edit", Entity: "agentProfile", Verb: "edit", Method: "PATCH", Path: "/projects/{p}/agent-profile",
		Summary:        "Change the agent profile; the rendered config files and AGENTS.md are committed to main",
		Description:    "Change the project's agent profile: driver (claude-code or opencode), model, permission preset, auto-merge policy for session branches, draft policy per entity kind, instructions template, or the AGENTS.md text itself (which makes the instructions custom). The rendered .claude/settings.json, opencode.json, AGENTS.md and CLAUDE.md are committed to main; running sessions pick them up at their next turn. Agents changing their own profile wait for an approval. Send ifMatch with the profile's etag.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "agentsMd", Type: "string", Description: "The AGENTS.md text; setting it makes the instructions custom (instructionsTemplate becomes custom)"},
			{Name: "autoMerge", Type: "string", Description: "when-clean: a session branch merges into main at session end when it applies cleanly; never: it always waits as Session changes"},
			{Name: "draftPolicy", Type: "object"},
			{Name: "driver", Type: "string"},
			{Name: "instructionsTemplate", Type: "string", Description: "An instructions template (templates.list templateKind=instructions): default or minimal; custom once AGENTS.md was edited by hand"},
			{Name: "model", Type: "string", Description: "The driver's own model id: a Claude Code alias (sonnet, opus, haiku) or opencode's provider/model"},
			{Name: "permissionPreset", Type: "string", Description: "A permission preset (templates.list templateKind=preset), e.g. guardrails-default"},
		}},
	},
	{
		ID: "agentProfile.get", Entity: "agentProfile", Verb: "get", Method: "GET", Path: "/projects/{p}/agent-profile",
		Summary: "The project's agent profile with the config files rendered from it",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
		},
	},
	{
		ID: "agentSessions.accept", Entity: "agentSessions", Verb: "accept", Method: "POST", Path: "/agent-sessions/{id}:accept",
		Summary:        "Merge the session branch into main as a whole and end the session",
		Description:    "Accept a session's changes: merge its branch session/<id> into main (fast-forward, or a merge commit; a conflict answers merge-conflict and changes nothing). The session must be paused or ended; a paused one ends. Agents cannot accept sessions: a person decides.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Agent session id (ses_…)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
	},
	{
		ID: "agentSessions.cancel", Entity: "agentSessions", Verb: "cancel", Method: "POST", Path: "/agent-sessions/{id}:cancel",
		Summary:        "Stop the session's current turn; with end, also end the session",
		Description:    "Stop the current turn of an agent session (the agent answers ACP session/cancel). With end=true the session also ends: its token is revoked and its branch merges per the project's auto-merge policy. Agents cannot cancel sessions.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Agent session id (ses_…)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: false, Properties: []BodyProperty{
			{Name: "end", Type: "boolean", Description: "Also end the session (done); its branch merges per the auto-merge policy"},
		}},
	},
	{
		ID: "agentSessions.get", Entity: "agentSessions", Verb: "get", Method: "GET", Path: "/agent-sessions/{id}",
		Summary: "Get an agent session with its state, budget and use, branch and merge state",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Agent session id (ses_…)"},
		},
	},
	{
		ID: "agentSessions.list", Entity: "agentSessions", Verb: "list", Method: "GET", Path: "/projects/{p}/agent-sessions",
		Summary: "The project's agent sessions, live ones first, then the most recently changed",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "state", In: "query", Flag: "state", Type: "string", Description: "Only sessions in this state; live means created, running, waiting_approval or paused", Enum: []string{"live", "created", "running", "waiting_approval", "paused", "done", "failed", "cancelled"}},
			{Name: "limit", In: "query", Flag: "limit", Type: "integer", Default: "50"},
		},
	},
	{
		ID: "agentSessions.new", Entity: "agentSessions", Verb: "new", Method: "POST", Path: "/projects/{p}/agent-sessions",
		Summary:        "Start Claude Code or opencode on its own branch session/<id> of the project repository",
		Description:    "Start an agent session in the project: interactive (a conversation) or read-only (one turn, no changes). Driver and model default to the project's agent profile. Agents cannot start sessions.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "driver", Type: "string"},
			{Name: "kind"},
			{Name: "model", Type: "string", Description: "Defaults to the agent profile's model (for the profile's driver) or the driver's default"},
			{Name: "prompt", Type: "string", Description: "The first message; required for read-only sessions"},
			{Name: "references", Type: "array of object"},
		}},
	},
	{
		ID: "agentSessions.pause", Entity: "agentSessions", Verb: "pause", Method: "POST", Path: "/agent-sessions/{id}:pause",
		Summary:        "Pause a session; the current turn stops, the worktree is committed and the agent process ends",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Agent session id (ses_…)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
	},
	{
		ID: "agentSessions.resume", Entity: "agentSessions", Verb: "resume", Method: "POST", Path: "/agent-sessions/{id}:resume",
		Summary:        "Resume a paused session (ACP session/resume, else a new ACP session with a transcript summary)",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Agent session id (ses_…)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: false, Properties: []BodyProperty{
			{Name: "budget", Type: "object", Description: "Raise the session budget (a session paused by its budget resumes only with room left)"},
		}},
	},
	{
		ID: "agentSessions.revert", Entity: "agentSessions", Verb: "revert", Method: "POST", Path: "/agent-sessions/{id}:revert",
		Summary:        "Discard the session branch as a whole and end the session",
		Description:    "Discard a session's changes: delete its branch session/<id>; main does not change. The session must be paused or ended; a paused one ends.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Agent session id (ses_…)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
	},
	{
		ID: "aliases.get", Entity: "aliases", Verb: "get", Method: "GET", Path: "/projects/{p}/aliases/{name}",
		Summary: "Get one project alias and the version it points at",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "name", In: "path", Flag: "name", Required: true, Type: "string", Description: "Alias name without the @ (train-current, baseline, …)"},
		},
	},
	{
		ID: "aliases.list", Entity: "aliases", Verb: "list", Method: "GET", Path: "/projects/{p}/aliases",
		Summary: "The project's aliases (train-current, baseline, production, …) and the versions they point at",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
		},
	},
	{
		ID: "aliases.set", Entity: "aliases", Verb: "set", Method: "PUT", Path: "/projects/{p}/aliases/{name}",
		Summary:        "Point a project alias at an adopted registry version (baseline is gated, production moves only by promotion)",
		Description:    "Point a project alias (@train-current, @baseline, or any free name) at a registry version the project has adopted (projects.adopt first). Pipelines reference aliases; runs record the resolved version. Moving baseline is gated and may answer 202 with an approval id (R8). production is read-only here: it answers 409 reserved-alias and moves only with deployments.promote. Send If-Match with the alias's revision (aliases.get) unless the alias does not exist yet.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "name", In: "path", Flag: "name", Required: true, Type: "string", Description: "Alias name without the @ (train-current, baseline, …)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Type: "string", Description: "The revision the change is based on; required unless the target does not exist yet"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "version", Required: true, Type: "string", Description: "A registry version the project adopted (ver_…)"},
		}},
	},
	{
		ID: "approvals.approve", Entity: "approvals", Verb: "approve", Method: "POST", Path: "/approvals/{id}:approve",
		Summary:        "Approve a pending request; the stored request runs as its original actor",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: false, Properties: []BodyProperty{
			{Name: "grant", Type: "string"},
			{Name: "note", Type: "string"},
		}},
	},
	{
		ID: "approvals.deny", Entity: "approvals", Verb: "deny", Method: "POST", Path: "/approvals/{id}:deny",
		Summary:        "Deny a pending request; it never runs",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: false, Properties: []BodyProperty{
			{Name: "note", Type: "string"},
		}},
	},
	{
		ID: "approvals.get", Entity: "approvals", Verb: "get", Method: "GET", Path: "/approvals/{id}",
		Summary: "Get an approval with its stored request and, once approved, the replay's result",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string"},
		},
	},
	{
		ID: "approvals.list", Entity: "approvals", Verb: "list", Method: "GET", Path: "/approvals",
		Summary:     "Approvals, pending first, then the most recently decided",
		Description: "Approvals: gated commands waiting for a person, pending first. Filter by state (pending, approved, denied, or decided for both) and project. An agent cannot decide approvals; it waits for the approval.decided event.",
		Params: []Param{
			{Name: "state", In: "query", Flag: "state", Type: "string", Description: "Only approvals in this state; decided means approved or denied", Enum: []string{"pending", "approved", "denied", "decided"}},
			{Name: "project", In: "query", Flag: "project", Type: "string", Description: "Project slug or id"},
			{Name: "limit", In: "query", Flag: "limit", Type: "integer", Default: "100"},
		},
	},
	{
		ID: "audit.list", Entity: "audit", Verb: "list", Method: "GET", Path: "/audit",
		Summary: "The audit log, newest first — every command, denial and failed attempt with its actor and cause",
		Params: []Param{
			{Name: "actor", In: "query", Flag: "actor", Type: "string", Description: "Actor id (usr_…"},
			{Name: "project", In: "query", Flag: "project", Type: "string", Description: "Project slug or id"},
			{Name: "operation", In: "query", Flag: "operation", Type: "string", Description: "Operation id, e.g. projects.archive"},
			{Name: "before", In: "query", Flag: "before", Type: "string", Description: "Cursor: the `next` value of the previous page"},
			{Name: "limit", In: "query", Flag: "limit", Type: "integer", Default: "100"},
		},
	},
	{
		ID: "baseModels.get", Entity: "baseModels", Verb: "get", Method: "GET", Path: "/registry/base-models/{id}",
		Summary: "Get a base model version with the projects that use it",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Registry version id (ver_…)"},
		},
	},
	{
		ID: "baseModels.list", Entity: "baseModels", Verb: "list", Method: "GET", Path: "/registry/base-models",
		Summary: "List base model versions (Hugging Face repository at a pinned revision, licence, model family)",
		Params: []Param{
			{Name: "collection", In: "query", Flag: "collection", Type: "string", Description: "Only versions of this collection (id reg_… or name, e.g. dataset/fleurs-he-smoke)"},
			{Name: "state", In: "query", Flag: "state", Type: "string", Description: "Only versions in this state", Enum: []string{"draft", "frozen", "deprecated"}},
		},
	},
	{
		ID: "branches.accept", Entity: "branches", Verb: "accept", Method: "POST", Path: "/projects/{p}/branches/{name}:accept",
		Summary:        "Merge a sync branch into main (fast-forward when possible, otherwise a merge commit)",
		Description:    "Merge a draft branch (sync/<date>) into main: fast-forward when main has not moved, otherwise a merge commit. A conflict answers 409 merge-conflict with the conflicting files and leaves main unchanged. Session branches are merged with agentSessions.accept. Send ifMatch with the branch head from branches.get, so you accept exactly what you reviewed.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "name", In: "path", Flag: "name", Required: true, Type: "string", Description: "Branch name, URL-encoded (sync%2F2026-09-30, session%2F<id>)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
	},
	{
		ID: "branches.compare", Entity: "branches", Verb: "compare", Method: "GET", Path: "/projects/{p}/branches/{name}:compare",
		Summary:     "A branch compared with main file by file in three ways (merge base, main, branch), with conflict hunks",
		Description: "Compare a session or sync branch with main per file: the merge base, main and branch versions (blob ids), whether each file merges cleanly and, for conflicting files, the three texts (each cut at 128 KiB) and the hunks that cover them, each marked same, main, branch, both or conflict. Use it to see why agentSessions.accept or branches.accept answered merge-conflict; resolve on the branch, then accept again.",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "name", In: "path", Flag: "name", Required: true, Type: "string", Description: "Branch name, URL-encoded (sync%2F2026-09-30, session%2F<id>)"},
		},
	},
	{
		ID: "branches.get", Entity: "branches", Verb: "get", Method: "GET", Path: "/projects/{p}/branches/{name}",
		Summary: "A branch with its diff against main and the conflicts a merge would meet",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "name", In: "path", Flag: "name", Required: true, Type: "string", Description: "Branch name, URL-encoded (sync%2F2026-09-30, session%2F<id>)"},
		},
	},
	{
		ID: "branches.list", Entity: "branches", Verb: "list", Method: "GET", Path: "/projects/{p}/branches",
		Summary: "Open branches of the project repository (session and sync branches not merged into main)",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
		},
	},
	{
		ID: "branches.revert", Entity: "branches", Verb: "revert", Method: "POST", Path: "/projects/{p}/branches/{name}:revert",
		Summary:        "Discard a sync branch without merging it",
		Description:    "Discard a draft branch (sync/<date>): the branch is deleted and main is unchanged. Session branches are discarded with agentSessions.revert. Send ifMatch with the branch head from branches.get.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "name", In: "path", Flag: "name", Required: true, Type: "string", Description: "Branch name, URL-encoded (sync%2F2026-09-30, session%2F<id>)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
	},
	{
		ID: "collections.get", Entity: "collections", Verb: "get", Method: "GET", Path: "/registry/collections/{id}",
		Summary: "Get a registry collection with its versions, newest first",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Collection id (reg_…) or name with the slash escaped (dataset%2Ffleurs-he-smoke)"},
		},
	},
	{
		ID: "collections.list", Entity: "collections", Verb: "list", Method: "GET", Path: "/registry/collections",
		Summary:     "List registry collections (named series of immutable versions), optionally of one kind or tag",
		Description: "List registry collections such as base-model/nemotron-3.5-asr-streaming-0.6b or dataset/fleurs-he-smoke. A collection groups immutable versions of one kind; list the versions with baseModels.list, datasets.list or templates.list (filter collection=<name>).",
		Params: []Param{
			{Name: "kind", In: "query", Flag: "kind", Type: "string", Description: "Only collections of this kind", Enum: []string{"base_model", "dataset_version", "template"}},
			{Name: "tag", In: "query", Flag: "tag", Type: "string", Description: "Only collections carrying this tag (e.g. locale:he-IL)"},
		},
	},
	{
		ID: "compute.edit", Entity: "compute", Verb: "edit", Method: "PATCH", Path: "/compute/{id}",
		Summary:        "Change a host's description or a card's memory cap and allowed job kinds",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Host id (cmp_…) or name (staging)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "cards", Type: "array of object"},
			{Name: "description", Type: "string"},
		}},
	},
	{
		ID: "compute.get", Entity: "compute", Verb: "get", Method: "GET", Path: "/compute/{id}",
		Summary: "Get a host and its cards",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Host id (cmp_…) or name (staging)"},
		},
	},
	{
		ID: "compute.list", Entity: "compute", Verb: "list", Method: "GET", Path: "/compute",
		Summary: "Hosts and their cards (memory cap per card, allowed job kinds) with health",
	},
	{
		ID: "credentials.list", Entity: "credentials", Verb: "list", Method: "GET", Path: "/credentials",
		Summary: "List credentials (sessions, API keys, agent tokens) without their secrets",
		Params: []Param{
			{Name: "kind", In: "query", Flag: "kind", Type: "string", Description: "Only this kind", Enum: []string{"session", "api_key", "agent", "agent_host", "invitation", "worker"}},
			{Name: "revoked", In: "query", Flag: "revoked", Type: "boolean", Description: "Include revoked and expired credentials", Default: "false"},
		},
	},
	{
		ID: "credentials.new", Entity: "credentials", Verb: "new", Method: "POST", Path: "/credentials",
		Summary:        "Create a personal API key (cdk_) scoped to one project or to registry read",
		Description:    "Create a personal API key (Bearer cdk_…) for automation and the CLI, scoped to one project or to reading the registry. The token is returned once, in this response only; Cadence stores its hash.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "expiresAt", Type: "string", Description: "Never expires when absent"},
			{Name: "name", Required: true, Type: "string"},
			{Name: "scope", Required: true, Type: "object", Description: "One project, registry read, or both"},
		}},
	},
	{
		ID: "credentials.revoke", Entity: "credentials", Verb: "revoke", Method: "POST", Path: "/credentials/{id}:revoke",
		Summary:        "Revoke a credential; requests carrying it are refused from now on (irreversible)",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
	},
	{
		ID: "datasets.get", Entity: "datasets", Verb: "get", Method: "GET", Path: "/registry/datasets/{id}",
		Summary: "Get a dataset version with its splits, statistics and the projects that use it",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Registry version id (ver_…)"},
		},
	},
	{
		ID: "datasets.list", Entity: "datasets", Verb: "list", Method: "GET", Path: "/registry/datasets",
		Summary: "List dataset versions (immutable, fingerprinted selections with splits and statistics)",
		Params: []Param{
			{Name: "collection", In: "query", Flag: "collection", Type: "string", Description: "Only versions of this collection (id reg_… or name, e.g. dataset/fleurs-he-smoke)"},
			{Name: "state", In: "query", Flag: "state", Type: "string", Description: "Only versions in this state", Enum: []string{"draft", "frozen", "deprecated"}},
		},
	},
	{
		ID: "defaults.get", Entity: "defaults", Verb: "get", Method: "GET", Path: "/defaults",
		Summary:     "The versioned defaults (defaults.yaml) every form, budget and estimate starts from",
		Description: "The defaults every parameter, form, budget and estimate starts from (defaults.yaml): each value with its description, source and safe range. A value written anywhere else that differs is a departure from default.",
	},
	{
		ID: "drafts.accept", Entity: "drafts", Verb: "accept", Method: "POST", Path: "/drafts/{id}:accept",
		Summary:        "Apply a draft as a new revision of its entity, attributed to the person who accepts it",
		Description:    "Accept a draft: its content becomes a new revision of the entity, attributed to the caller, with causedBy naming the draft. Send ifMatch with the draft's etag (rev). A draft whose entity moved on since it was made fails with draft-stale and the entity's current revision. Agents may not accept drafts: a person decides.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Draft id (drf_…)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
	},
	{
		ID: "drafts.get", Entity: "drafts", Verb: "get", Method: "GET", Path: "/drafts/{id}",
		Summary: "Get a draft with its changes against the revision it was based on",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Draft id (drf_…)"},
		},
	},
	{
		ID: "drafts.list", Entity: "drafts", Verb: "list", Method: "GET", Path: "/drafts",
		Summary: "Drafts of one entity (open ones by default), newest first",
		Params: []Param{
			{Name: "entityKind", In: "query", Flag: "entity-kind", Required: true, Type: "string", Description: "Kind of the drafted entity", Enum: []string{"mix"}},
			{Name: "entityId", In: "query", Flag: "entity-id", Required: true, Type: "string", Description: "Id of the drafted entity (mix_…)"},
			{Name: "state", In: "query", Flag: "state", Type: "string", Description: "Only drafts in this state; all lists every state", Default: "open", Enum: []string{"open", "accepted", "reverted", "all"}},
		},
	},
	{
		ID: "drafts.revert", Entity: "drafts", Verb: "revert", Method: "POST", Path: "/drafts/{id}:revert",
		Summary:        "Discard a draft; its entity stays as it is",
		Description:    "Revert (discard) a draft; the entity does not change. Send ifMatch with the draft's etag (rev).",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Draft id (drf_…)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
	},
	{
		ID: "events.list", Entity: "events", Verb: "list", Method: "GET", Path: "/events",
		Summary:     "Events after a sequence number; with Accept text/event-stream, the live stream",
		Description: "Events after a sequence number, oldest first, optionally filtered by topic patterns (a trailing * matches the remaining segments, e.g. run.123.*) and project. Use the last seq as `after` to continue.",
		Params: []Param{
			{Name: "topics", In: "query", Flag: "topics", Type: "string", Description: "Comma-separated topic patterns; a trailing `*` matches one or more segments. Default all."},
			{Name: "project", In: "query", Flag: "project", Type: "string", Description: "Keep work events of this project (registry events, which carry no projectId, always pass)"},
			{Name: "after", In: "query", Flag: "after", Type: "integer", Description: "Only events with seq greater than this; SSE clients may send Last-Event-ID instead"},
			{Name: "limit", In: "query", Flag: "limit", Type: "integer", Description: "Page size for the JSON form", Default: "200"},
		},
	},
	{
		ID: "help.get", Entity: "help", Verb: "get", Method: "GET", Path: "/help/{id}",
		Summary:     "Get a help article (markdown)",
		Description: "Get a help article (markdown) by id <section>.<slug>. Every error a tool returns names its article (errors.<slug>): read it for what went wrong and how to fix it.",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "<section>.<slug>, e.g. errors.not-found, panels.library"},
		},
	},
	{
		ID: "help.search", Entity: "help", Verb: "search", Method: "GET", Path: "/help",
		Summary: "Search help articles by text or by context (panel, step kind, error type, field)",
		Params: []Param{
			{Name: "q", In: "query", Flag: "q", Type: "string", Description: "Free text"},
			{Name: "context", In: "query", Flag: "context", Type: "string", Description: "Qualifier of the place the user is in: panel:<id>, step:<kind>, error:<slug>, field:<path>"},
			{Name: "limit", In: "query", Flag: "limit", Type: "integer", Default: "20"},
		},
	},
	{
		ID: "jobs.cancel", Entity: "jobs", Verb: "cancel", Method: "POST", Path: "/jobs/{id}:cancel",
		Summary:        "Cancel a job; a queued job stops at once, a running one when its handler notices",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
	},
	{
		ID: "jobs.get", Entity: "jobs", Verb: "get", Method: "GET", Path: "/jobs/{id}",
		Summary: "Get a job",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string"},
		},
	},
	{
		ID: "jobs.list", Entity: "jobs", Verb: "list", Method: "GET", Path: "/projects/{p}/jobs",
		Summary: "Jobs of a project, newest first",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "state", In: "query", Flag: "state", Type: "string", Description: "Only jobs in this state", Enum: []string{"queued", "running", "done", "failed", "cancelled"}},
			{Name: "limit", In: "query", Flag: "limit", Type: "integer", Default: "100"},
		},
	},
	{
		ID: "jobs.wait", Entity: "jobs", Verb: "wait", Method: "GET", Path: "/jobs/{id}:wait",
		Summary:     "Wait until a job ends or the timeout passes, then return it (agents)",
		Description: "Wait for a job started by another tool (which answered 202 with a jobId). Returns the job as soon as it is done, failed or cancelled, or when the timeout (seconds, at most 60) passes — check `state` and call again if it is still queued or running.",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string"},
			{Name: "timeout", In: "query", Flag: "timeout", Type: "integer", Description: "Seconds to wait at most", Default: "30"},
		},
	},
	{
		ID: "mixes.edit", Entity: "mixes", Verb: "edit", Method: "PATCH", Path: "/mixes/{id}",
		Summary:        "Edit a mix; a person's edit makes a new revision, an agent's lands as a draft when the draft policy says so",
		Description:    "Edit a mix: the fields you send replace the current ones (groups as a whole list). Send ifMatch with the etag (or rev) of your last mixes.get; a stale revision fails with precondition-failed and the current revision. Under the project's draft policy (the default for agents) the edit does not change the mix: it lands as a draft (result.draft) that a person accepts or reverts, and your later edits update the same draft. mixes.get shows your open draft under presence.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Mix id (mix_…)"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "description", Type: "string"},
			{Name: "groups", Type: "array of object"},
			{Name: "name", Type: "string"},
			{Name: "replayShare", Type: "number"},
			{Name: "temperature", Type: "number"},
		}},
	},
	{
		ID: "mixes.get", Entity: "mixes", Verb: "get", Method: "GET", Path: "/mixes/{id}",
		Summary: "Get a mix at its current revision, with its preview and who is editing it",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Mix id (mix_…)"},
		},
	},
	{
		ID: "mixes.list", Entity: "mixes", Verb: "list", Method: "GET", Path: "/projects/{p}/mixes",
		Summary: "The project's mixes, most recently changed first",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
		},
	},
	{
		ID: "mixes.new", Entity: "mixes", Verb: "new", Method: "POST", Path: "/projects/{p}/mixes",
		Summary:        "Save a new mix (groups over dataset versions, weights, temperature, replay share) at revision 1",
		Description:    "Save a new mix: named groups of frozen dataset versions (ver_…, @alias or a collection name such as dataset/fleurs-he-smoke, resolved to its newest frozen version), each with a weight, plus the sampling temperature and the replay share. Omitted values come from defaults.yaml (defaults://). Call mixes.preview first to see hours per language. A mix is project work with revisions (R13).",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "description", Type: "string"},
			{Name: "groups", Required: true, Type: "array of object"},
			{Name: "name", Required: true, Type: "string", Description: "Unique within the project"},
			{Name: "replayShare", Type: "number", Description: "Share of samples drawn from replay groups; mix.replay_share of defaults.yaml when the mix has a replay group, else 0"},
			{Name: "temperature", Type: "number", Description: "Sampling temperature over group weights (probability ∝ weight^(1/temperature)); mix.temperature of defaults.yaml when omitted"},
		}},
	},
	{
		ID: "mixes.preview", Entity: "mixes", Verb: "preview", Method: "POST", Path: "/projects/{p}/mixes:preview",
		Summary:        "Hours per language and sampling shares of a mix without saving it (metadata only, no GPU)",
		Description:    "Preview a mix without saving it: the source hours of every group and language and the share of training samples each would get under the weights, temperature and replay share. Reads dataset-version metadata only; nothing is written and no GPU is used.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "description", Type: "string"},
			{Name: "groups", Required: true, Type: "array of object"},
			{Name: "name", Required: true, Type: "string", Description: "Unique within the project"},
			{Name: "replayShare", Type: "number", Description: "Share of samples drawn from replay groups; mix.replay_share of defaults.yaml when the mix has a replay group, else 0"},
			{Name: "temperature", Type: "number", Description: "Sampling temperature over group weights (probability ∝ weight^(1/temperature)); mix.temperature of defaults.yaml when omitted"},
		}},
	},
	{
		ID: "policies.edit", Entity: "policies", Verb: "edit", Method: "PATCH", Path: "/policies",
		Summary:        "Change instance-wide policies; values must stay inside the ranges in defaults.yaml",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "budgets", Type: "object"},
		}},
	},
	{
		ID: "policies.get", Entity: "policies", Verb: "get", Method: "GET", Path: "/policies",
		Summary: "Instance-wide policies (budgets now; retention, PII and cache quotas later)",
	},
	{
		ID: "projects.adopt", Entity: "projects", Verb: "adopt", Method: "POST", Path: "/projects/{p}:adopt",
		Summary:        "Adopt a registry version into the project by reference",
		Description:    "Adopt a registry version (base model, dataset version, template) into this project by reference, so mixes, runs and aliases may use it. Only frozen versions are adoptable. Needs If-Match with the project's revision (projects.get); the project's revision goes up by one.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "version", Required: true, Type: "string", Description: "The registry version to adopt (ver_…)"},
		}},
	},
	{
		ID: "projects.archive", Entity: "projects", Verb: "archive", Method: "POST", Path: "/projects/{p}:archive",
		Summary:        "Archive a project (soft; reversible)",
		Description:    "Archive a project (soft; reversible): it leaves the default projects.list but still resolves by slug; its server-side worktrees and working clone are removed and its repository becomes read-only (no more commits or pushes). Send ifMatch with the etag (or rev) of your last projects.get.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
	},
	{
		ID: "projects.edit", Entity: "projects", Verb: "edit", Method: "PATCH", Path: "/projects/{p}",
		Summary:        "Change a project's name, description, locales, domain, base model or budgets",
		Description:    "Change what the wizard set: name, description, locales, domain, the default base model (a frozen base-model version id; it is adopted when it is not yet) and budgets. Changes to project facts re-render project.yaml and AGENTS.md and commit them to main. Send ifMatch with the etag (or rev) of your last projects.get; a stale revision fails with precondition-failed and the current revision to re-read.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "baseModel", Type: "string", Description: "A frozen base-model version id (ver_…); adopted when the project has not yet"},
			{Name: "budgets", Type: "object"},
			{Name: "description", Type: "string"},
			{Name: "domain", Type: "string"},
			{Name: "locales", Type: "array of string"},
			{Name: "name", Type: "string"},
		}},
	},
	{
		ID: "projects.get", Entity: "projects", Verb: "get", Method: "GET", Path: "/projects/{p}",
		Summary: "Get a project",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
		},
	},
	{
		ID: "projects.list", Entity: "projects", Verb: "list", Method: "GET", Path: "/projects",
		Summary: "List projects",
		Params: []Param{
			{Name: "archived", In: "query", Flag: "archived", Type: "boolean", Description: "Include archived projects", Default: "false"},
		},
	},
	{
		ID: "projects.new", Entity: "projects", Verb: "new", Method: "POST", Path: "/projects",
		Summary:        "Create a project from the wizard's choices and bootstrap its repository (202 with the bootstrap job)",
		Description:    "Create a project: a unit of work with its own repository, budgets and gates. Only name is required; every other wizard choice (slug, locales, domain, base model, agent driver and model, permission preset, instructions template, repository, budgets) defaults from defaults.yaml (defaults.get, section wizard). The project is created in state bootstrapping and the answer is 202 with the bootstrap job's id: follow job.{jobId} (jobs.wait) until the repository is written and the project is active. A dry run answers 200 with the project that would be created and queues nothing.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "agent", Type: "object"},
			{Name: "baseModel", Type: "string", Description: "A frozen base-model version id (ver_…) or collection name (its newest frozen version)"},
			{Name: "budgets", Type: "object"},
			{Name: "description", Type: "string"},
			{Name: "domain", Type: "string"},
			{Name: "instructionsTemplate", Type: "string", Description: "An instructions template (templates.list templateKind=instructions): default or minimal; custom once AGENTS.md was edited by hand"},
			{Name: "locales", Type: "array of string"},
			{Name: "name", Required: true, Type: "string"},
			{Name: "repository", Type: "object"},
			{Name: "slug", Type: "string", Description: "Lowercase letters, digits and dashes; 3–40 characters"},
		}},
	},
	{
		ID: "projects.note", Entity: "projects", Verb: "note", Method: "POST", Path: "/projects/{p}:note",
		Summary:        "Append a dated learning to the project's NOTES.md and commit it to main",
		Description:    "Record a learning for the next session: the text is appended to NOTES.md under today's date and committed to main; AGENTS.md tells every session to read NOTES.md. Keep one learning per note, in a sentence or two (what was tried, what happened, what to do next time). Send ifMatch with the project's etag (projects.get); the project's revision goes up by one.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "text", Required: true, Type: "string", Description: "One learning in a sentence or two; Markdown"},
		}},
	},
	{
		ID: "projects.search", Entity: "projects", Verb: "search", Method: "GET", Path: "/projects/{p}:search",
		Summary:     "Search entities of this project and the registry with free text and qualifiers",
		Description: "Search what Cadence knows — projects, mixes, registry versions and collections, jobs, approvals, help articles — from this project. q is free text (typos and identifiers match by trigram; Hebrew is matched without niqqud) plus qualifiers: kind:<kind>[,<kind>] (e.g. kind:dataset_version,job), status:<s> (alias state:), lang:<locale> (he matches he-IL), actor:agent|user|automation|<id>, updated:>2026-09-01 (also <, >=, <=, a day, or a..b), project:<slug> or scope:all|project|registry, tag:<tag>, alias:@<name>, and numeric comparisons such as wer<10, progress>=0.5 or dur:2..8. Without a scope qualifier the search covers this project and the registry. Results are grouped by kind, this project's newest first. An unknown qualifier answers invalid-query with the list of qualifiers.",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "q", In: "query", Flag: "q", Type: "string", Description: "Free text plus qualifiers, e.g. `fleurs kind:dataset_version tag:telephony updated:>2026-09-01`"},
			{Name: "limit", In: "query", Flag: "limit", Type: "integer", Description: "Most hits returned over all groups", Default: "50"},
		},
	},
	{
		ID: "projects.sync", Entity: "projects", Verb: "sync", Method: "POST", Path: "/projects/{p}:sync",
		Summary:        "Diff the project against Cadence's current templates and skills and offer the update as a draft branch",
		Description:    "Re-render every file the bootstrap wrote from templates (skills, starter pipelines, agent config, AGENTS.md unless it is custom, data.lock) with the current template versions and compare with main. When anything differs the update is committed on a new branch sync/<date> as a draft: review it with branches.get and apply it with branches.accept or drop it with branches.revert. A dry run lists the changes only. Send ifMatch with the project's etag (projects.get).",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "If-Match", In: "header", Flag: "if-match", Required: true, Type: "string", Description: "The revision the change is based on (the ETag of the last read); a mismatch answers 412 with currentRev"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
	},
	{
		ID: "recipes.get", Entity: "recipes", Verb: "get", Method: "GET", Path: "/projects/{p}/recipes/{path}",
		Summary: "One file of the project repository at a branch or commit, with its commit history",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "path", In: "path", Flag: "path", Required: true, Type: "string", Description: "File path in the repository, URL-encoded (pipelines%2Ftrain-stage.yaml)"},
			{Name: "ref", In: "query", Flag: "ref", Type: "string", Description: "Branch (main, session/<id>, sync/<date>) or commit sha to read at; main when absent"},
		},
	},
	{
		ID: "recipes.list", Entity: "recipes", Verb: "list", Method: "GET", Path: "/projects/{p}/recipes",
		Summary: "Files of the project repository at a branch or commit",
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "ref", In: "query", Flag: "ref", Type: "string", Description: "Branch (main, session/<id>, sync/<date>) or commit sha to read at; main when absent"},
			{Name: "prefix", In: "query", Flag: "prefix", Type: "string", Description: "Only files under this directory, e.g. pipelines/"},
		},
	},
	{
		ID: "registry.search", Entity: "registry", Verb: "search", Method: "GET", Path: "/registry",
		Summary:     "Search registry versions of every kind by text and qualifiers (kind:, tag:, locale:, state:)",
		Description: "Search registry versions of every kind (base models, dataset versions, templates). q is free text matched against collection names and descriptions plus qualifiers: kind:base_model, tag:telephony, locale:he-IL, state:frozen. project=<slug> keeps only what that project adopted. Get one version with baseModels.get, datasets.get or templates.get.",
		Params: []Param{
			{Name: "q", In: "query", Flag: "q", Type: "string", Description: "Free text with qualifiers (kind:, tag:, locale:, state:)"},
			{Name: "kind", In: "query", Flag: "kind", Type: "string", Enum: []string{"base_model", "dataset_version", "template"}},
			{Name: "project", In: "query", Flag: "project", Type: "string", Description: "Only versions this project adopted (slug)"},
			{Name: "limit", In: "query", Flag: "limit", Type: "integer", Default: "100"},
		},
	},
	{
		ID: "runs.new", Entity: "runs", Verb: "new", Method: "POST", Path: "/projects/{p}/runs",
		Summary:        "Start a training run; until phase 2 only ?dryRun=true answers, with GPU-hours, card, duration and data",
		Description:    "Start a training run from a base model (init base) or a checkpoint. Until phase 2 only the dry run works: call it with dryRun=true to get the estimate (GPU-hours, duration, card, data volume, basis and ±) from the defaults table and the compute entity; without dryRun it answers 501.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "p", In: "path", Flag: "project", Required: true, Type: "string", Description: "Project slug"},
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "baseModel", Type: "string", Description: "Base model version (ver_…), collection name (its newest frozen version) or @alias; default the defaults' base model"},
			{Name: "checkpoint", Type: "string", Description: "Required when init is checkpoint (checkpoints arrive in phase 2)"},
			{Name: "compute", Type: "string", Description: "Host id or name; default the first host whose card allows training"},
			{Name: "datasets", Type: "array of string", Description: "Dataset versions (ver_… or @alias) the run reads, for the data volume; the mix replaces this in phase 2"},
			{Name: "gpus", Type: "integer", Description: "Cards for the run; v1 accepts 1 (training.gpus)"},
			{Name: "init", Type: "string", Description: "Where the weights start (R44); scratch is deferred"},
			{Name: "precision", Type: "string"},
			{Name: "steps", Type: "integer", Description: "Default training.steps"},
		}},
	},
	{
		ID: "secrets.list", Entity: "secrets", Verb: "list", Method: "GET", Path: "/secrets",
		Summary: "Named credentials (name, kind, scope, last use); values are never returned",
	},
	{
		ID: "secrets.new", Entity: "secrets", Verb: "new", Method: "POST", Path: "/secrets",
		Summary:        "Store a named credential; the value is write-only and never returned",
		Description:    "Store a named credential (Hugging Face, NGC, GitHub, S3, judge API). The value is encrypted at rest outside the database and never returned by any operation; jobs and bootstrap read it on the server. Agents should not call this: secrets never enter an agent context.",
		IdempotencyKey: true,
		Params: []Param{
			{Name: "dryRun", In: "query", Flag: "dry-run", Type: "boolean", Description: "Validate and report what would happen without changing anything", Default: "false"},
		},
		Body: &Body{Required: true, Properties: []BodyProperty{
			{Name: "kind", Required: true, Type: "string"},
			{Name: "name", Required: true, Type: "string"},
			{Name: "scope", Type: "string", Description: "instance, or project:<slug> when only that project's jobs and bootstrap may read it"},
			{Name: "value", Required: true, Type: "string", Description: "Write-only; stored encrypted outside the database"},
		}},
	},
	{
		ID: "templates.get", Entity: "templates", Verb: "get", Method: "GET", Path: "/registry/templates/{id}",
		Summary: "Get a template version with its files (paths and hashes) and the projects that use it",
		Params: []Param{
			{Name: "id", In: "path", Flag: "id", Required: true, Type: "string", Description: "Registry version id (ver_…)"},
		},
	},
	{
		ID: "templates.list", Entity: "templates", Verb: "list", Method: "GET", Path: "/registry/templates",
		Summary: "List template versions (instruction templates, permission presets, skills, pipeline templates, agent config)",
		Params: []Param{
			{Name: "collection", In: "query", Flag: "collection", Type: "string", Description: "Only versions of this collection (id reg_… or name, e.g. dataset/fleurs-he-smoke)"},
			{Name: "state", In: "query", Flag: "state", Type: "string", Description: "Only versions in this state", Enum: []string{"draft", "frozen", "deprecated"}},
			{Name: "templateKind", In: "query", Flag: "template-kind", Type: "string", Description: "Only templates of this kind", Enum: []string{"instructions", "preset", "skill", "pipeline", "agent-config"}},
		},
	},
}
