"""Writes web/src/shell/audio/colormaps.gen.ts: the audio view's 256-entry RGB lookup tables (R52), from matplotlib's
tables (BSD-style licence; the perceptually uniform maps are CC0 by van der Walt, Smith and Nuñez; cividis by Nuñez,
Anderton and Renslow, 2018). Run once when the list changes:

  uvx --with matplotlib==3.10.* --with numpy python web/scripts/colormaps.py web/src/shell/audio/colormaps.gen.ts
"""

from __future__ import annotations

import base64
import sys

import numpy as np
from matplotlib import colormaps

NAMES = ("magma", "viridis", "cividis", "inferno")
lines = [
    "// Generated by web/scripts/colormaps.py (matplotlib's tables): 256 RGB triplets per map, base64. Do not edit.",
    "// Order is the lookup texture's row order; the shader indexes rows by position.",
    "export const COLORMAP_TABLES = {",
]
for name in NAMES:
    rgb = (colormaps[name](np.linspace(0, 1, 256))[:, :3] * 255).round().astype(np.uint8)
    lines.append(f'  {name}: "{base64.b64encode(rgb.tobytes()).decode()}",')
grey = np.repeat(np.arange(256, dtype=np.uint8)[:, None], 3, 1)
lines.append(f'  grey: "{base64.b64encode(grey.tobytes()).decode()}",')
lines.append(f'  "grey-inverse": "{base64.b64encode(grey[::-1].copy().tobytes()).decode()}",')
lines.append("} as const;")
open(sys.argv[1], "w").write("\n".join(lines) + "\n")
