"""Spike S5: write the 256x1 colour lookup tables (magma, viridis, grey) as a TypeScript module (run once)."""

from __future__ import annotations

import base64
import sys

import numpy as np
from matplotlib import colormaps

lines = ["// Generated by docs/spikes/s5/colormaps.py (matplotlib's tables): 256 RGB triplets, base64."]
for name in ("magma", "viridis"):
    rgb = (colormaps[name](np.linspace(0, 1, 256))[:, :3] * 255).round().astype(np.uint8)
    lines.append(f'export const {name.upper()} = "{base64.b64encode(rgb.tobytes()).decode()}";')
grey = np.repeat(np.arange(256, dtype=np.uint8)[:, None], 3, 1)
lines.append(f'export const GREY = "{base64.b64encode(grey.tobytes()).decode()}";')
open(sys.argv[1], "w").write("\n".join(lines) + "\n")
