// Code generated by control-plane/cmd/mcpgen from api/openapi.yaml. DO NOT EDIT.

package api

import (
	"context"
	"strconv"
)

// Planned answers 501 for operations named in the contract but implemented in a later phase.
// Embed it in the server; implementing an operation shadows its method here.
type Planned struct{}

// PlannedOperations maps each planned operationId to the roadmap phase that implements it.
var PlannedOperations = map[string]int{
	"agentMessages.new":    1,
	"agentSessions.cancel": 1,
	"agentSessions.new":    1,
	"approvals.approve":    1,
	"approvals.deny":       1,
	"approvals.list":       1,
	"jobs.cancel":          1,
	"jobs.get":             1,
	"mixes.edit":           2,
	"mixes.new":            2,
	"mixes.preview":        2,
	"mounts.list":          4,
	"mounts.new":           4,
}

func plannedProblem(opID string, phase int) Problem {
	detail := opID + " is planned for roadmap phase " + strconv.Itoa(phase) + " and not implemented yet"
	return Problem{Type: "https://cadence.local/help/errors/not-implemented", Title: "Not implemented", Status: 501, Detail: &detail}
}

// AgentMessagesNew answers 501 until phase 1.
func (Planned) AgentMessagesNew(_ context.Context, _ AgentMessagesNewRequestObject) (AgentMessagesNewResponseObject, error) {
	return AgentMessagesNewdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("agentMessages.new", 1), StatusCode: 501}, nil
}

// AgentSessionsCancel answers 501 until phase 1.
func (Planned) AgentSessionsCancel(_ context.Context, _ AgentSessionsCancelRequestObject) (AgentSessionsCancelResponseObject, error) {
	return AgentSessionsCanceldefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("agentSessions.cancel", 1), StatusCode: 501}, nil
}

// AgentSessionsNew answers 501 until phase 1.
func (Planned) AgentSessionsNew(_ context.Context, _ AgentSessionsNewRequestObject) (AgentSessionsNewResponseObject, error) {
	return AgentSessionsNewdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("agentSessions.new", 1), StatusCode: 501}, nil
}

// ApprovalsApprove answers 501 until phase 1.
func (Planned) ApprovalsApprove(_ context.Context, _ ApprovalsApproveRequestObject) (ApprovalsApproveResponseObject, error) {
	return ApprovalsApprovedefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("approvals.approve", 1), StatusCode: 501}, nil
}

// ApprovalsDeny answers 501 until phase 1.
func (Planned) ApprovalsDeny(_ context.Context, _ ApprovalsDenyRequestObject) (ApprovalsDenyResponseObject, error) {
	return ApprovalsDenydefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("approvals.deny", 1), StatusCode: 501}, nil
}

// ApprovalsList answers 501 until phase 1.
func (Planned) ApprovalsList(_ context.Context, _ ApprovalsListRequestObject) (ApprovalsListResponseObject, error) {
	return ApprovalsListdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("approvals.list", 1), StatusCode: 501}, nil
}

// JobsCancel answers 501 until phase 1.
func (Planned) JobsCancel(_ context.Context, _ JobsCancelRequestObject) (JobsCancelResponseObject, error) {
	return JobsCanceldefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("jobs.cancel", 1), StatusCode: 501}, nil
}

// JobsGet answers 501 until phase 1.
func (Planned) JobsGet(_ context.Context, _ JobsGetRequestObject) (JobsGetResponseObject, error) {
	return JobsGetdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("jobs.get", 1), StatusCode: 501}, nil
}

// MixesEdit answers 501 until phase 2.
func (Planned) MixesEdit(_ context.Context, _ MixesEditRequestObject) (MixesEditResponseObject, error) {
	return MixesEditdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("mixes.edit", 2), StatusCode: 501}, nil
}

// MixesNew answers 501 until phase 2.
func (Planned) MixesNew(_ context.Context, _ MixesNewRequestObject) (MixesNewResponseObject, error) {
	return MixesNewdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("mixes.new", 2), StatusCode: 501}, nil
}

// MixesPreview answers 501 until phase 2.
func (Planned) MixesPreview(_ context.Context, _ MixesPreviewRequestObject) (MixesPreviewResponseObject, error) {
	return MixesPreviewdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("mixes.preview", 2), StatusCode: 501}, nil
}

// MountsList answers 501 until phase 4.
func (Planned) MountsList(_ context.Context, _ MountsListRequestObject) (MountsListResponseObject, error) {
	return MountsListdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("mounts.list", 4), StatusCode: 501}, nil
}

// MountsNew answers 501 until phase 4.
func (Planned) MountsNew(_ context.Context, _ MountsNewRequestObject) (MountsNewResponseObject, error) {
	return MountsNewdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("mounts.new", 4), StatusCode: 501}, nil
}
