// Code generated by control-plane/cmd/mcpgen from api/openapi.yaml. DO NOT EDIT.

package api

import (
	"context"
	"strconv"
)

// Planned answers 501 for operations named in the contract but implemented in a later phase.
// Embed it in the server; implementing an operation shadows its method here.
type Planned struct{}

// PlannedOperations maps each planned operationId to the roadmap phase that implements it.
var PlannedOperations = map[string]int{
	"agentMessages.new":    1,
	"agentSessions.cancel": 1,
	"agentSessions.new":    1,
	"aliases.set":          1,
	"mixes.edit":           2,
	"mixes.new":            2,
	"mixes.preview":        2,
	"mounts.list":          4,
	"mounts.new":           4,
	"runs.new":             2,
}

func plannedProblem(opID string, phase int) Problem {
	detail := opID + " is planned for roadmap phase " + strconv.Itoa(phase) + " and not implemented yet"
	return Problem{Type: "https://cadence.local/help/errors/not-implemented", Title: "Not implemented", Status: 501, Detail: &detail}
}

// AgentMessagesNew answers 501 until phase 1.
func (Planned) AgentMessagesNew(_ context.Context, _ AgentMessagesNewRequestObject) (AgentMessagesNewResponseObject, error) {
	return AgentMessagesNewdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("agentMessages.new", 1), StatusCode: 501}, nil
}

// AgentSessionsCancel answers 501 until phase 1.
func (Planned) AgentSessionsCancel(_ context.Context, _ AgentSessionsCancelRequestObject) (AgentSessionsCancelResponseObject, error) {
	return AgentSessionsCanceldefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("agentSessions.cancel", 1), StatusCode: 501}, nil
}

// AgentSessionsNew answers 501 until phase 1.
func (Planned) AgentSessionsNew(_ context.Context, _ AgentSessionsNewRequestObject) (AgentSessionsNewResponseObject, error) {
	return AgentSessionsNewdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("agentSessions.new", 1), StatusCode: 501}, nil
}

// AliasesSet answers 501 until phase 1.
func (Planned) AliasesSet(_ context.Context, _ AliasesSetRequestObject) (AliasesSetResponseObject, error) {
	return AliasesSetdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("aliases.set", 1), StatusCode: 501}, nil
}

// MixesEdit answers 501 until phase 2.
func (Planned) MixesEdit(_ context.Context, _ MixesEditRequestObject) (MixesEditResponseObject, error) {
	return MixesEditdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("mixes.edit", 2), StatusCode: 501}, nil
}

// MixesNew answers 501 until phase 2.
func (Planned) MixesNew(_ context.Context, _ MixesNewRequestObject) (MixesNewResponseObject, error) {
	return MixesNewdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("mixes.new", 2), StatusCode: 501}, nil
}

// MixesPreview answers 501 until phase 2.
func (Planned) MixesPreview(_ context.Context, _ MixesPreviewRequestObject) (MixesPreviewResponseObject, error) {
	return MixesPreviewdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("mixes.preview", 2), StatusCode: 501}, nil
}

// MountsList answers 501 until phase 4.
func (Planned) MountsList(_ context.Context, _ MountsListRequestObject) (MountsListResponseObject, error) {
	return MountsListdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("mounts.list", 4), StatusCode: 501}, nil
}

// MountsNew answers 501 until phase 4.
func (Planned) MountsNew(_ context.Context, _ MountsNewRequestObject) (MountsNewResponseObject, error) {
	return MountsNewdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("mounts.new", 4), StatusCode: 501}, nil
}

// RunsNew answers 501 until phase 2.
func (Planned) RunsNew(_ context.Context, _ RunsNewRequestObject) (RunsNewResponseObject, error) {
	return RunsNewdefaultApplicationProblemPlusJSONResponse{Body: plannedProblem("runs.new", 2), StatusCode: 501}, nil
}
