"""E1 step 3b: write a Triton model repository for one exported step graph — the shape of what the NeMo pack's
Triton repository builder should produce (R46).

  python3 docs/spikes/e1/triton/build_repo.py <onnx_dir> <repo_dir> [--name nemotron_step] [--max-batch 64]
      [--instances 1] [--queue-us 1000] [--accel none|trt-fp16] [--gpu-mem-gb 8] [--direct] [--plan engine.plan]

One model, the sequence batcher with implicit state (the k2-fsa streaming Zipformer pattern): every stream's encoder
caches, prediction-network state and last token live in Triton's state buffers between requests; a request carries
one feature buffer (`audio_signal` [128, T], `length`, `prompt`) and returns the chunk's tokens. START is wired to the
graph's `start` input, which resets the state in-graph. Nothing runs in Python. Backend: ONNX Runtime on step.onnx
(CUDA EP, optionally its TensorRT EP), or the TensorRT backend on an engine trtexec built from the same graph.
"""

from __future__ import annotations

import argparse
import json
import os

T_STATE = {"cache_last_channel_len": "TYPE_INT64", "last_token": "TYPE_INT64"}


def config(geo: dict, name: str, max_batch: int, instances: int, queue_us: int, accel: str, mem_gb: float,
           direct: bool = False, plan: bool = False, growable: bool = False) -> str:
    strategy = (f"direct {{ max_queue_delay_microseconds: {queue_us} }}" if direct else
                f"oldest {{ max_candidate_sequences: 1024 max_queue_delay_microseconds: {queue_us} }}")
    T, M = geo["buffer_frames"], geo["n_mels"]
    states = []
    for n, dims in geo["state_shapes"].items():
        dt = "TYPE_FP32" if geo.get("float_state") else T_STATE.get(n, "TYPE_FP32")
        d = ", ".join(str(v) for v in dims)
        i_name, o_name = geo.get("state_io", {}).get(n, [n, f"{n}_next"])
        keep = " use_same_buffer_for_input_output: true use_growable_memory: true" if growable else ""
        states.append(
            f'    {{ input_name: "{i_name}" output_name: "{o_name}" data_type: {dt} dims: [ {d} ]{keep}\n'
            f'      initial_state: {{ data_type: {dt} dims: [ {d} ] zero_data: true name: "zero_{i_name}" }} }}'
        )
    n_tok = geo["valid_out_len"] * geo["max_symbols"] if isinstance(geo["valid_out_len"], int) else -1
    if plan:  # TensorRT backend: the engine trtexec built from the same graph; ORT parameters do not apply
        backend, params = 'platform: "tensorrt_plan"', ""
    else:
        backend = 'backend: "onnxruntime"'
        params = ""
        if accel == "cuda-notf32":  # strict fp32 matmuls, as NeMo's matmul_precision "highest" (ORT defaults to TF32)
            params += (
                "optimization { execution_accelerators { gpu_execution_accelerator: [ { name: \"cuda\"\n"
                "  parameters { key: \"use_tf32\" value: \"0\" } } ] } }\n"
            )
        if accel == "trt-fp16":
            params += (
                "optimization { execution_accelerators { gpu_execution_accelerator: [ { name: \"tensorrt\"\n"
                "  parameters { key: \"precision_mode\" value: \"FP16\" }\n"
                "  parameters { key: \"max_workspace_size_bytes\" value: \"2147483648\" }\n"
                "  parameters { key: \"trt_engine_cache_enable\" value: \"1\" }\n"
                "  parameters { key: \"trt_engine_cache_path\" value: \"/tmp/trtcache\" } } ] } }\n"
            )
        params += (
            f'parameters {{ key: "gpu_mem_limit" value: {{ string_value: "{int(mem_gb * 1024**3)}" }} }}\n'
            # 1 = kSameAsRequested (A3's value), 0 = kNextPowerOfTwo (ORT's default): ORT_ARENA picks
            f'parameters {{ key: "arena_extend_strategy" value: {{ string_value: "{os.environ.get("ORT_ARENA", "1")}" }} }}\n'
            'parameters { key: "cudnn_conv_algo_search" value: { string_value: "0" } }\n'
        )
    sep = "," + chr(10)
    return f"""# Generated by docs/spikes/e1/triton/build_repo.py from {geo.get('precision', 'fp32')} step.onnx, profile {geo['chunk_ms']} ms
# (att_context_size {geo['att_context_size']}): buffer {T} frames = pre-encode cache + chunk; {n_tok} token slots per request.
name: "{name}"
{backend}
max_batch_size: {max_batch}
sequence_batching {{
  max_sequence_idle_microseconds: 60000000
  {strategy}
  control_input [
    {{ name: "start" control [ {{ kind: CONTROL_SEQUENCE_START int32_false_true: [ 0, 1 ] }} ] }}
  ]
  state [
{sep.join(states)}
  ]
}}
input [
  {{ name: "audio_signal" data_type: TYPE_FP32 dims: [ {M}, {T} ] }},
  {{ name: "length" data_type: TYPE_INT64 dims: [ 1 ] }},
  {{ name: "prompt" data_type: TYPE_INT64 dims: [ 1 ] }}
]
output [
  {{ name: "tokens" data_type: TYPE_INT32 dims: [ {n_tok} ] }},
  {{ name: "encoded_len" data_type: TYPE_INT64 dims: [ 1 ] }}
]
instance_group [ {{ count: {instances} kind: KIND_GPU gpus: [ 0 ] }} ]
{params}"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("onnx_dir")
    ap.add_argument("repo")
    ap.add_argument("--name", default="nemotron_step")
    ap.add_argument("--max-batch", type=int, default=64)
    ap.add_argument("--instances", type=int, default=1)
    ap.add_argument("--queue-us", type=int, default=1000)
    ap.add_argument("--accel", default="none")
    ap.add_argument("--gpu-mem-gb", type=float, default=8.0)
    ap.add_argument("--direct", action="store_true")
    ap.add_argument("--growable", action="store_true", help="state buffers stay in CUDA memory (one buffer in and out)")
    ap.add_argument("--plan", default="", help="a TensorRT engine built from step.onnx (trtexec): serve it instead")
    a = ap.parse_args()
    geo = json.load(open(os.path.join(a.onnx_dir, "streaming_cfg.json")))
    d = os.path.join(a.repo, a.name)
    os.makedirs(os.path.join(d, "1"), exist_ok=True)
    files = [(a.plan, "model.plan")] if a.plan else [
        (os.path.join(a.onnx_dir, "step.onnx"), "model.onnx"),
        (os.path.join(a.onnx_dir, "step.onnx.data"), "step.onnx.data"),
    ]
    for src, dst in files:
        p = os.path.join(d, "1", dst)
        if os.path.exists(p):
            os.remove(p)
        os.link(src, p)  # hard link: the graph names its data file, no second copy
    with open(os.path.join(d, "config.pbtxt"), "w") as f:
        f.write(config(geo, a.name, a.max_batch, a.instances, a.queue_us, a.accel, a.gpu_mem_gb, a.direct,
                       bool(a.plan), a.growable))
    with open(os.path.join(d, "streaming_cfg.json"), "w") as f:
        json.dump(geo, f, indent=1)
    print(open(os.path.join(d, "config.pbtxt")).read())


if __name__ == "__main__":
    main()
