package contract

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// cliGlobalFlags are the flags every generated CLI command has; a parameter may not take their names.
var cliGlobalFlags = []string{"url", "token", "body", "idempotency-key", "help"}

// CLIFlag is the command-line flag of a parameter: kebab-case of its name, except the project slug path parameter
// `p`, which reads `--project`. If-Match is `--if-match`; Idempotency-Key and other transport headers are not flags.
func CLIFlag(p *openapi3.Parameter) (string, bool) {
	switch {
	case p.In == "header" && strings.EqualFold(p.Name, "If-Match"):
		return "if-match", true
	case p.In == "header":
		return "", false
	case p.In == "path" && p.Name == "p":
		return "project", true
	}
	return Kebab(p.Name), true
}

// CLIGo renders the operation table of the generated CLI (R34, docs/spec/08-resolutions.md): every implemented
// operation outside the exempt tags, with its flags and body properties. The runtime lives in internal/cli.
func (c *Contract) CLIGo() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by control-plane/cmd/mcpgen from api/openapi.yaml. DO NOT EDIT.\n\n")
	b.WriteString("package cli\n\n")
	b.WriteString("// Operations are the commands `cadence <entity> <verb>`: every implemented operation outside the exempt tags.\n")
	b.WriteString("var Operations = []Operation{\n")
	for _, o := range c.Ops {
		if o.Exempt || o.Planned > 0 {
			continue
		}
		if err := writeCLIOp(&b, o); err != nil {
			return nil, err
		}
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

func writeCLIOp(b *bytes.Buffer, o *Operation) error {
	_, takesKey := o.paramRef("header", "Idempotency-Key")
	desc := strings.Join(strings.Fields(o.ToolDesc), " ")
	fmt.Fprintf(b, "\t{\n\t\tID: %q, Entity: %q, Verb: %q, Method: %q, Path: %q,\n", o.ID, o.Entity, o.Verb, o.Method, o.Path)
	fmt.Fprintf(b, "\t\tSummary: %q,\n", o.Summary)
	if desc != "" {
		fmt.Fprintf(b, "\t\tDescription: %q,\n", desc)
	}
	if takesKey {
		b.WriteString("\t\tIdempotencyKey: true,\n")
	}
	seen := map[string]string{}
	for _, g := range cliGlobalFlags {
		seen[g] = "a global flag"
	}
	var params []string
	for _, p := range o.params() {
		flag, ok := CLIFlag(p)
		if !ok {
			continue
		}
		if prev, dup := seen[flag]; dup {
			return fmt.Errorf("%s: parameter %s %q would take the flag --%s, already %s", o.ID, p.In, p.Name, flag, prev)
		}
		seen[flag] = fmt.Sprintf("parameter %s %q", p.In, p.Name)
		params = append(params, cliParam(p, flag))
	}
	if len(params) > 0 {
		b.WriteString("\t\tParams: []Param{\n")
		for _, p := range params {
			b.WriteString("\t\t\t" + p + ",\n")
		}
		b.WriteString("\t\t},\n")
	}
	if rb := o.op.RequestBody; rb != nil && rb.Value != nil {
		if mt := rb.Value.Content.Get("application/json"); mt != nil {
			fmt.Fprintf(b, "\t\tBody: &Body{Required: %t", rb.Value.Required)
			if props := cliBodyProps(mt.Schema); len(props) > 0 {
				b.WriteString(", Properties: []BodyProperty{\n")
				for _, p := range props {
					b.WriteString("\t\t\t" + p + ",\n")
				}
				b.WriteString("\t\t}")
			}
			b.WriteString("},\n")
		}
	}
	b.WriteString("\t},\n")
	return nil
}

func cliParam(p *openapi3.Parameter, flag string) string {
	var f []string
	f = append(f, fmt.Sprintf("Name: %q, In: %q, Flag: %q", p.Name, p.In, flag))
	if p.Required {
		f = append(f, "Required: true")
	}
	typ, items, def, enum := schemaFacts(p.Schema)
	if typ != "" {
		f = append(f, fmt.Sprintf("Type: %q", typ))
	}
	if items != "" {
		f = append(f, fmt.Sprintf("Items: %q", items))
	}
	if desc := strings.Join(strings.Fields(p.Description), " "); desc != "" {
		f = append(f, fmt.Sprintf("Description: %q", desc))
	}
	if def != "" {
		f = append(f, fmt.Sprintf("Default: %q", def))
	}
	if len(enum) > 0 {
		f = append(f, fmt.Sprintf("Enum: %#v", enum))
	}
	return "{" + strings.Join(f, ", ") + "}"
}

func cliBodyProps(ref *openapi3.SchemaRef) []string {
	if ref == nil || ref.Value == nil {
		return nil
	}
	s := ref.Value
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}
	names := make([]string, 0, len(s.Properties))
	for n := range s.Properties {
		names = append(names, n)
	}
	sort.Strings(names)
	out := make([]string, 0, len(names))
	for _, n := range names {
		p := s.Properties[n]
		f := []string{fmt.Sprintf("Name: %q", n)}
		if required[n] {
			f = append(f, "Required: true")
		}
		typ, items, _, _ := schemaFacts(p)
		if typ == "array" && items != "" {
			typ = "array of " + items
		}
		if typ != "" {
			f = append(f, fmt.Sprintf("Type: %q", typ))
		}
		if p != nil && p.Value != nil {
			if desc := strings.Join(strings.Fields(p.Value.Description), " "); desc != "" {
				f = append(f, fmt.Sprintf("Description: %q", desc))
			}
		}
		out = append(out, "{"+strings.Join(f, ", ")+"}")
	}
	return out
}

// schemaFacts reads a parameter or property schema's type (object for a $ref'd object), item type, default and enum.
func schemaFacts(ref *openapi3.SchemaRef) (typ, items, def string, enum []string) {
	if ref == nil || ref.Value == nil {
		return "", "", "", nil
	}
	s := ref.Value
	if s.Type != nil && len(*s.Type) > 0 {
		typ = (*s.Type)[0]
	} else if len(s.Properties) > 0 {
		typ = "object"
	}
	if s.Items != nil && s.Items.Value != nil && s.Items.Value.Type != nil && len(*s.Items.Value.Type) > 0 {
		items = (*s.Items.Value.Type)[0]
	}
	if s.Default != nil {
		def = fmt.Sprint(s.Default)
	}
	for _, e := range s.Enum {
		enum = append(enum, fmt.Sprint(e))
	}
	return typ, items, def, enum
}
