"""Synthesise the toy pack's fixture clips: each letter is a short tone at its own pitch, a space is silence, plus a
little noise. Deterministic; the output is committed under cadence_toy/fixtures (CC0, generated by this script) as an
import folder in the ``folder-csv`` format of ``dataset_import`` (``metadata.csv`` with file, text, split): the
conformance suite and the pack's tests import it into a ``dataset`` artifact first.

    uv run python packs/toy/scripts/make_fixtures.py
"""

from __future__ import annotations

import csv
import math
import random
import struct
import wave
from pathlib import Path

RATE = 16000
OUT = Path(__file__).resolve().parents[1] / "cadence_toy" / "fixtures"
TEXTS = [
    "a bad cab",
    "dead beef",
    "face a cafe",
    "bead",
    "fade",
    "deaf bee",
    "a decade",
    "cab fee",
]
LETTER_MS, GAP_MS, SPACE_MS, EDGE_MS = 80, 20, 60, 100


def tone_hz(ch: str) -> float:
    # Linear spacing keeps neighbouring letters in different mel bands (a = 300 Hz, f = 1700 Hz, z = 7300 Hz).
    return 300.0 + 280.0 * (ord(ch) - ord("a"))


def synth(text: str, rng: random.Random) -> list[float]:
    out = [0.0] * (RATE * EDGE_MS // 1000)
    for ch in text:
        if ch == " ":
            # A word boundary is a short burst of broadband noise between silences: unlike any letter's tone.
            n = RATE * LETTER_MS // 1000
            out += [0.0] * (RATE * GAP_MS // 1000)
            out += [rng.gauss(0, 0.15) * math.sin(math.pi * i / n) for i in range(n)]
            out += [0.0] * (RATE * SPACE_MS // 1000)
            continue
        n = RATE * LETTER_MS // 1000
        f = tone_hz(ch)
        out += [0.5 * math.sin(2 * math.pi * f * i / RATE) * math.sin(math.pi * i / n) for i in range(n)]
        out += [0.0] * (RATE * GAP_MS // 1000)
    out += [0.0] * (RATE * EDGE_MS // 1000)
    return [s + rng.gauss(0, 0.005) for s in out]


def write(path: Path, samples: list[float]) -> None:
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(b"".join(struct.pack("<h", max(-32768, min(32767, int(s * 32767)))) for s in samples))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    rng = random.Random(1234)
    rows = []
    for i, text in enumerate(TEXTS, 1):
        name = f"clip{i:02d}.wav"
        write(OUT / name, synth(text, rng))
        rows.append({"file": name, "text": text, "split": "train"})
    with (OUT / "metadata.csv").open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["file", "text", "split"], lineterminator="\n")
        w.writeheader()
        w.writerows(rows)


if __name__ == "__main__":
    main()
